<form action="/admin/addSubmit" method="post">
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name">
    </div>

    <div class="form-group">
        <label for="time">Cooking time</label>
        <input type="number" class="form-control" id="time">
    </div>

    <div class="form-group">
        <label for="ingredients">Ingredients</label>
        <textarea class="form-control" id="ingredients" placeholder="Enter a comma separated list of ingredients" rows="3"></textarea>
    </div>

    <input class="btn btn-primary" type="submit" value="Add" />
</form>
