<table class="table table-striped">
<thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Time</th>
        <th scope="col">Ingredients</th>
    </tr>
</thead>
<tbody>
    <tr>
        <td>Arroz con pollo</td>
        <td>1:00h</td>
        <td>Rice, Chicken, Bijol</td>
    </tr>
    <tr>
        <td>Fried Rice</td>
        <td>1:30h</td>
        <td>Rice, Shrimp, Onions, Peper, Eggs, Ham, Chinese beans, Garlic, Soy Souce</td>
    </tr>
</tbody>
</table>