

    





    
        <!-- Search Form -->
        <div class="row">
        <div class="col-md-12 padding">
            <form action="/index/searchSubmit" method="post">
                <div class="row">
                    <div class="input-group col-md-4">
                        <input class="form-control py-2" type="search" value="search" id="search">
                        <span class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Search Results -->
<div class="container">
    <div class="row">

        <!-- column 1 -->
        <div class="col ">
            <div class="card-div">
                <div class="card-header">
                    <div class="time">1:12</div>
                </div>
                <a class="card-bg card-block" style="background-image: url(https://www.comedera.com/wp-content/uploads/2013/07/arroz-con-pollo.jpg);"></a>
            <div>

            <div class="card-user">
                <div class="card-title">
                    <div class="card-name">
                        <div><a href="#">Arroz Con Pollo</a></div>
                        <div class="card-subname">Cuban Style</div>
                    </div>
                    <div class="card-fav">
                        <a href="#"><i class="fas fa-heart"></i></a>
                    </div>
                </div>
                
                <div class="card-ingredients">
                    <div class="black underline">ingredients </div>Rice, Chicken, Bijol
                </div>
            </div>

            <div class="card-info-wrap"><hr/>
                <ul class="card-info">
                    <li class="card-info-details">
                        <a href="#" title="views">
                            <span class="card-info-label card-block">Views</span>
                            <span class="card-info-value">9.840</span>
                        </a>
                    </li>
                    <li class="card-info-details">
                        <a href="#" title="reviews">
                            <span class="card-info-label card-block">Reviews</span>
                            <span class="card-info-value">885</span>
                        </a>
                    </li>
                    <li class="card-info-details">
                        <a href="#" title="shared">
                            <span class="card-info-label card-block">Shared</span>
                            <span class="card-info-value">1.810</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>











        <!-- Column 2 -->
        <div class="col ">
            <div class="card-div">
                <div class="card-header">
                    <div class="time">1:00</div>
                </div>
                <a class="card-bg card-block" style="background-image: url(https://i.ytimg.com/vi/7AxydboW8v8/maxresdefault.jpg);"></a>
            <div>

            <div class="card-user">
                <div class="card-title">
                    <div class="card-name">
                        <div><a href="#">Fried Rice</a></div>
                        <div class="card-subname">Chinese</div>
                    </div>
                    <div class="card-fav">
                        <a href="#"><i class="fas fa-heart"></i></a>
                    </div>
                </div>
                
                <div class="card-ingredients">
                    <div class="black underline">ingredients </div>Rice, Shrimp, Onions, Peper, Eggs, Ham, Chinese beans, Garlic, Soy Souce
                </div>
            </div>

            <div class="card-info-wrap"><hr/>
                <ul class="card-info">
                    <li class="card-info-details">
                        <a href="#" title="views">
                            <span class="card-info-label card-block">Views</span>
                            <span class="card-info-value">4.840</span>
                        </a>
                    </li>
                    <li class="card-info-details">
                        <a href="#" title="reviews">
                            <span class="card-info-label card-block">Reviews</span>
                            <span class="card-info-value">285</span>
                        </a>
                    </li>
                    <li class="card-info-details">
                        <a href="#" title="shared">
                            <span class="card-info-label card-block">Shared</span>
                            <span class="card-info-value">1.110</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>






        <!-- Column 3 -->
        <div class="col ">
            <div class="card-div">
                <div class="card-header">
                    <div class="time">0:30</div>
                </div>
                <a class="card-bg card-block" style="background-image: url(https://images-gmi-pmc.edge-generalmills.com/e3d3c44c-5148-4996-a26d-abc952d7e9cc.jpg);"></a>
            <div>

            <div class="card-user">
                <div class="card-title">
                    <div class="card-name">
                        <div><a href="#">Chili</a></div>
                        <div class="card-subname">Spicy Turkey</div>
                    </div>
                    <div class="card-fav">
                        <a href="#"><i class="fas fa-heart"></i></a>
                    </div>
                </div>
                
                <div class="card-ingredients">
                    <div class="black underline">ingredients </div>Red beans, turkey, corn, jalapenos, shredded cheese, onions, green peppers, tomato chunks, salsa
                </div>
            </div>

            <div class="card-info-wrap"><hr/>
                <ul class="card-info">
                    <li class="card-info-details">
                        <a href="#" title="views">
                            <span class="card-info-label card-block">Views</span>
                            <span class="card-info-value">9.940</span>
                        </a>
                    </li>
                    <li class="card-info-details">
                        <a href="#" title="reviews">
                            <span class="card-info-label card-block">Reviews</span>
                            <span class="card-info-value">1085</span>
                        </a>
                    </li>
                    <li class="card-info-details">
                        <a href="#" title="shared">
                            <span class="card-info-label card-block">Shared</span>
                            <span class="card-info-value">2.810</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>