
    </div>
</div>

<!-- Recipe View -->

    <div style="height: 100vh; background-image: url(https://www.comedera.com/wp-content/uploads/2013/07/arroz-con-pollo.jpg); background-size: cover;">
    
   <div class = "container">
       <div class = "row" style="background: #ccc; width: 50%; padding: 40px 5px 20px 20px; opacity: .8;">

            <div><h1 style="text-align: left;">Arroz con Pollo</h1><span style="text-align: right; color: #fff; font-size: 3rem;">1:12</span></div>
        </div>
        <div class="row" style="background: #ccc; width: 50%; height: 100%; margin-top: 60px; padding: 40px 5px 20px 20px; opacity: .8;">
            <p style="padding: 40px 5px 20px 20px; opacity: .8; font-size: 40px;">
                Ingredients:
            
                <span style="font-size: 30px;">Rice, Chicken, Bijol</span>
            </p>
        </div>
        <div class="row" style="background: #ccc; width: 50%; height: 100%; margin-top: 60px; padding: 40px 5px 20px 20px; opacity: .8;">
            <p style="padding: 40px 5px 20px 20px; opacity: .8; font-size: 40px;">
                Instructions:
            
                <span style="font-size: 30px;">blah, blah, blah, blah, blah, blah, blah, blah, blah</span>
            </p>
        </div>
   </div>
</div>
</div>


