<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login | Tasty Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <!--navbar -->
            <div class="col-sm-12" style="margin-bottom:20px;">
                <nav class="navbar navbar-dark bg-dark">
                    <a class="navbar-brand" href="#">TASTY.APP</a>
                </nav>
            </div>

            <!--content -->
            <div class="col-sm-12">
                <h1>Login</h1>
                <br/>
                <?= $this->getContent() ?>
            </div>
        </div>
    </div>
</body>
</html>
